### PR TITLE
Update Crucible and related deps

### PR DESCRIPTION
**Pull request by pfmooney**

### CODE REVIEW

**Comment by leftwo** [comment]
I think we got one more Crucible PR we hope to land today!  Hold!  Hold!

**Review by hawkw — APPROVED** [review]

**Comment by pfmooney** [comment]
> I think we got one more Crucible PR we hope to land today! Hold! Hold!

Will do.  What's the PR we should wait for?

**Comment by leftwo** [comment]
https://github.com/oxidecomputer/crucible/pull/1087
Waiting on one last review.

**Comment by leftwo** [comment]
It's in,

New hash: 2d4bc11232d53f177c286383926fa5f8c1b2a938

**Pull request merged**
