### PR TITLE
bump Crucible rev

### PR DESCRIPTION
**Pull request by gjcolombo**
Tested: local PHD run including Crucible tests.

### CODE REVIEW

**Comment by gjcolombo** [comment]
The CI failure here is a rustc segfault encountered while building the `dladm` crate. This appears to have been introduced by moving to rustc 1.69.0. Moving to the latest compatible version of `num_enum` (which has some codegen improvements that reduce its stack consumption) seems to resolve the issue. Will have that change pushed shortly.

**Review by leftwo — APPROVED** [review]
If this passes your PHD tests, (and the image builds in CI) then you have my rubber stamp :)

**Review by smklein — APPROVED** [review]
Thanks for the bump!

**Comment by gjcolombo** [comment]
Another successful hour at the software factory!

**Pull request merged**
