### PR TITLE
Make license headers consistent (and checked)

### PR DESCRIPTION
**Pull request by pfmooney**

### CODE REVIEW

**Review by leftwo — COMMENTED** [review]
Is there a way you can check the repo for licenses outside of github?  
Like from the command line?

**Comment by pfmooney** [comment]
> Is there a way you can check the repo for licenses outside of github? Like from the command line?

Maybe?  The skywalking-eyes tool from the github action can be downloaded and run locally.  I just started with what Hubris had put in place.

**Comment by pfmooney** [comment]
There, now there's an extremely crude xtask for it.

**Review by leftwo — APPROVED** [review]
Thanks for adding the local xtask for this!

**Pull request merged**
