### PR TITLE
Add auto-destruct interface

### PR DESCRIPTION
**Pull request by pfmooney**

### CODE REVIEW

**Comment by pfmooney** [comment]
It should be ready for PHD and friends to consume once the underlying machine has been updated to bits which include the necessary illumos-gate change.

**Review by gjcolombo — APPROVED** [review]
Thanks for putting this together!

**Comment by luqmana** [comment]
Which were the upstream bits needed for this?

**Comment by pfmooney** [comment]
> Which were the upstream bits needed for this?

illumos/illumos-gate@aa39f6d0fd4e491afca04b12f49a18ce955efc79

**Pull request merged**
