### PR TITLE
PciPath to Bdf conversion is infallible; prove it and refactor

### PR DESCRIPTION
**Pull request by iximeow**
i initially tried to find `TryInto` cases by deleting the impl and seeing what broke, but clippy is much better at this than me. `cargo xtask clippy`, in fact, is something i forgot i can or should run.

### CODE REVIEW

**Review by gjcolombo — APPROVED** [review]
Nice!

**Review by pfmooney — APPROVED** [review]
Out of curiosity, how long does that test run on a modern CPU?

**Comment by iximeow** [comment]
i'd mostly just noticed it didn't "feel slow", but on second look it's 1.87s on a 7950x. so maybe it's more "not slow if you've just also been waiting to rebuild propolis"..

**Comment by pfmooney** [comment]
> i'd mostly just noticed it didn't "feel slow", but on second look it's 1.87s on a 7950x. so maybe it's more "not slow if you've just also been waiting to rebuild propolis"..

Seems reasonable enough.  If it becomes a problem in the future, we could rub some `quickcheck` (or similar) on it.

**Pull request merged**
